### ISSUE TITLE
Merge Error - Object Cannot be cast from DBNull to other types.

### ISSUE THREAD

**Issue by And-r3y** [AntonyCorbett/JWLMerge#1]
I encountered the following error while trying to merge two backups.
At first i though that my backup's were old ( which they were, like 5-6 months ), but then again i tried with backups made today. Still the same error.

Let me know if I can provide anything else except this error log

[log-20180122.txt](https://github.com/AntonyCorbett/JWLMerge/files/1651796/log-20180122.txt)

**Comment by AntonyCorbett** [comment]
@And-r3y - thanks for the feedback. A problem with certain types of bookmark. Fixed in latest release.
