### ISSUE TITLE
Merging Incomplete

### ISSUE THREAD

**Issue by CCHawkes** [AntonyCorbett/JWLMerge#10]
**Describe the bug**
**Three files from iPhone 7, iPad pro 10.5 and Windows JWLibrary… did not completely merge apparently...**

**To Reproduce**
3. See error
 In troubleshooting, it appears that these highlights are not being brought into the Windows version. Tried on both the iPhone and iPads and they all imported fine... except for the tag.

**Expected behavior**
**expected all three to merge into one file... it shows that is has with merge but tested first on Windows JWLibrary and, for ex: all the highlights from Jn 20 & 21 were not available... also, tag number in Windows was 73 not 74 as shown in Merged**...

**Screenshots**

**Desktop (please complete the following information):**
 - **Windows version 10... latest update...**
 - Other important information about your environment
**Running on Mac in Parallels**
Would have uploaded the jwpub backup files so you could examine them but GitHub doesn't allow that type of file for upload...

Thanks in advance for any help or suggestions....

**Comment by AntonyCorbett** [comment]
@CCHawkes Thanks for feedback. I can't diagnose this without the original 3 files, If they don't contain personal data you can upload them here (just change the extension to ".zip"). Or you can send the files to the SoundBox help desk: https://soundbox.on.spiceworks.com/portal

>  tag number in Windows was 73 not 74 as shown in Merged... < Please explain in more detail what "tag number" refers to and what "as shown in Merged..." means. 

Thanks
Antony

**Comment by CCHawkes** [comment]
Hi Anthony…

Tag number is the Number of tags under details for each file that is to be merged… 

Here are the attached files… Let me know if you don’t get them… 

CCH

**Comment by CCHawkes** [comment]
Also, here is the resulting merge file

**Comment by AntonyCorbett** [comment]
@CCHawkes there are no files.

**Comment by CCHawkes** [comment]
Hmmm…. Alright. Let me upload them to your SoundBox site then…

**Comment by CCHawkes** [comment]
Just sent to sound box portal…

CCH

**Comment by AntonyCorbett** [comment]
@CCHawkes I have replied on the portal. I'm having difficulty identifying the problem. The files you sent don't correspond to those cited above, so please give a clear example of data that is missing from the merged file you sent ("Merge 004 11-6-2018.jwlibrary"). Thanks for your help. 

Kind regards
Antony

**Comment by CCHawkes** [comment]
Anthony:

Here are the files just changed to a .zip from .jwlibrary type file. 
While the Tag issued seems to be OK, still, for some reason, in the Windows version (running in parallels on my MacBook) does not get my current highlights for John 20 and 21. However, all my iOS devices have the highlighting. I thought that with the merge, all iterations of comments, highlights ect would be merged and hence be the same on all devices once the merge file was restored.... do I understand the process correctly? The problem is probably with me, but I appreciate your help with this...

YB,
Craig

[UserDataBackup_2018-11-07_CRAIG-MACBOOK.zip](https://github.com/AntonyCorbett/JWLMerge/files/2560443/UserDataBackup_2018-11-07_CRAIG-MACBOOK.zip)
[UserDataBackup_2018-11-07_CCH-iPad-Pro-2.zip](https://github.com/AntonyCorbett/JWLMerge/files/2560444/UserDataBackup_2018-11-07_CCH-iPad-Pro-2.zip)
[UserDataBackup_2018-11-07_Craig-s-iPhone.zip](https://github.com/AntonyCorbett/JWLMerge/files/2560445/UserDataBackup_2018-11-07_Craig-s-iPhone.zip)
[UserDataBackup_2018-11-07_CCH-iPad-10-5.zip](https://github.com/AntonyCorbett/JWLMerge/files/2560446/UserDataBackup_2018-11-07_CCH-iPad-10-5.zip)
[Merge 005 11-7-2018.zip](https://github.com/AntonyCorbett/JWLMerge/files/2560447/Merge.005.11-7-2018.zip)

**Comment by CCHawkes** [comment]
I re-did all the above just to verify that the omission of highlights from John 20 & 21 in the Windows JWLibrary was occurring. When I restored the Merge file to all the iOS devices, the John 20 & 21 highlights were all there... but they were not present in the Windows JWLibrary app after I restored the merge file to it.

**Comment by AntonyCorbett** [comment]
Hi Craig

Yes, your understanding is correct. I tested here and it works fine on my Windows installation of the app. Your underlines in John 20 and 21 are all there, I suspect there may be a corruption of the JWL database on your Windows machine. You can fix this by using the "Reset" function in Windows "Apps and features" => JW Library => Advanced options. This will reset JWL to its original state (no documents, etc) and a clean database. Then download the study Bible and import your merged backup.

**Comment by CCHawkes** [comment]
Thanks Anthony… That fixed it! Appreciate your efforts…

**Comment by CCHawkes** [comment]
Beautiful!!!! Got it! Windows JW Library reset did it. Thanks Anthony!

**Comment by CCHawkes** [comment]
Sorry, didn't see that my past thanks posted :-)

**Comment by CCHawkes** [comment]
Hi Anthony…

This is the only way I could figure to get a thought out to you. Hope it’s ok…

I was wondering if you or anyone you know has developed a way to print out the spiritual gems in JWLibrary…

I’ve got so many notes in there and considering some of the comments by Brother Sanderson at the AM, they would be gems that I would like to place in safe keeping… 

Thanks in advance… and BTW, continue to love and appreciate JWLMerge… excellent tool!

YB,

Craig

**Comment by AntonyCorbett** [comment]
@CCHawkes You may have tried this already, but in JWLMerge click on Details => Note. Click in any cell of the grid and then press Ctrl-A to select all content. Copy to clipboard (Ctrl-C) and then paset into a Spreadsheet.

**Comment by CCHawkes** [comment]
Excellent! Works easily… just need to clean it up a bit… Thanks for the tip… I had looked at the notes before but didn’t scroll enough to the right!

CCH
