### ISSUE TITLE
Bible notes titles limited to 50 chars

### ISSUE THREAD

**Issue by temporarium** [AntonyCorbett/JWLMerge#13]
Is the 50-character limit for the titles set in stone (limited by the field size in the JWLibrary file), or is there a possibility you could remove/increase it, perhaps taking every first line as note title?

**Comment by Astasian** [comment]
In the db is no limitation for the length of titles, it's a hard coded limit in the app

**Comment by AntonyCorbett** [comment]
@temporarium from the Wiki: "The remaining content is the body of your note. You can use mutliple lines. If the first line of a multi-line note is less that or equal to 50 characters in length then it is used as the note's title."

**Comment by AntonyCorbett** [comment]
@temporarium not sure there's much we can do without modifying the format to allow for an explicit title attribute.

**Comment by temporarium** [comment]
HI @AntonyCorbett 
Is the only limitation here related to how JWLMerge is implemented?
If so, would it be hard to implement something like I suggested in another thread:

As for importing, it could be as simple as implementing a title line for each note enclosed in {{}}, which could in addition include a comma-separated list of tags? Something like: {{First Prophecy|Prophecy,Genesis}}

**Comment by tripLr** [comment]
Is it possible to import your merge utility to a bash script or other Linux
script

IE
Merge file1 with file 2 output file3

Is this just a simple database merge ?

Off topic question
Also when I mirror my devices the download folder has a different root
folder for the sdcard. Ie, old card
0000-0000/android/data/org.jwlibrary

New card
A2FC-1ACD/android/data/org.jwlibrary

 When i " restore " jwlibrary from the cloud or a backup onto a new device

The app looses where the existing files are downloaded and in have to
delete them and re download them.

Is there a way to

Search old jwlibrary location
Output that to a replace function in the database
And rewrite the broken links ?

Ideas.
Your brother.
triplr
