### ISSUE TITLE
Tagging imported Bible notes

### ISSUE THREAD

**Issue by temporarium** [AntonyCorbett/JWLMerge#14]
Is there any way to tag the imported notes?

For example, you could implement a title line for each note enclosed in {{}}, which could in addition include a comma-separated list of tags? Something like: {{Title|Tag1,Tag2}}

**Comment by ilikelinux69** [comment]
Tags you have to create when you make your notes in the App on the specific device.

Comfortably edit them you can in the section "Personal Study" (create, rename & delete).

If you keep a strict pattern (spelling) creating them, they will apear as you type while searching and separate them with blanks.

Maybe you just have to mark your "title tag_" with a special character and type it always first while searching in personal study.

In my opinion, too much similar and redundant tags makes it more difficult to work with it.

**Comment by AntonyCorbett** [comment]
@temporarium You can now specify a single, existing tag when importing a notes file. I know this doesn't really satisfy your request, but just for your information.

**Comment by temporarium** [comment]
HI Antony,

Thank you for the recent modifications. I was waiting to finish with Revelation before uploading my close-to-10-thousands notes...

Anyway, the tagging seems to work. The note in the reference pane shows the tag, but when the tag is selected in the study notes window, they're not listed. Maybe it's just very slow with so many notes.

No matter. My main purpose was to be able to eliminate ALL my Bible reference notes by tag, but that won't work anyway. I sometimes modify the title and so have a duplicate note, so I thought I'd remove them all first and reimport. So, to remove, I've resorted to an SQLite browser. It works, but it's a real tangle, and I hope I don't mess something up.

For the moment I've decided to prefix the titles with a "%". That way, in the SQLite browser, I can distinguish those notes from other notes I create directly in the app.

I have another strange issue: the notes show correctly in the reference pane - each one within its scripture section. But, in the Bible, I only have one note icon at the beginning of the chapter. This only happens in the nws-S. The Rbi8-S and the nwt-E display a note icon at each verse that has a note. The notes were imported with

[BibleKeySymbol=nwt]
[MepsLanguageId=1]

Any ideas? Could be just the app.

Anyway, thank you again for your continued work on this tool!

**Comment by temporarium** [comment]
Follow-up: I tried importing my notes as 

[BibleKeySymbol=nwtsty]
[MepsLanguageId=0]

And it worked!

**Comment by AntonyCorbett** [comment]
> I have another strange issue: the notes show correctly in the reference pane - each one within its scripture section. But, in the Bible, I only have one note icon at the beginning of the chapter. This only happens in the nwt-S. The Rbi8-S and the nwt-E display a note icon at each verse that has a note. 

Fixed

**Comment by temporarium** [comment]
So, was that a bug in your implementation, then?

Strangely, specifying the language, etc. has no impact, as the notes show up in all Bibles.

**Comment by AntonyCorbett** [comment]
> So, was that a bug in your implementation, then?

Yes
