### ISSUE TITLE
Port to Android / IOS / Linux

### ISSUE THREAD

**Issue by ilikelinux69** [AntonyCorbett/JWLMerge#15]
Would like to know if there is already a version for Android available or if there are plans / knowledge to do so in future?

My thoughts are that with Virtualbox and Android all 3 Operating systems could be served already today. And maybe it would accelerate a sync function itself in JWL?

If someone knows already other projects who achieve the same as JWLMerge please let me know.
I am also on Twitter with the same nickname.

**Comment by ilikelinux69** [comment]
I made some tests running the program in Wine (Linux - Fedora 30). Till now i had no luck. the log file stops there writing temp files (as user ctjones15 reported). I use Android with newest JWL on my Mobile devices where i wanted to merge the backups.

 _Do i need some special runtime libraries ?_

I installed the .net framework as asked by the installation.

**Comment by tripLr** [comment]
if we find out the database/language the merge the merger file is written in, there is probably aleady an open source tool to database merge <file> to <file>

at a minimum, a diff <file a> <file B> | tee diff.log should be able to be done

**Comment by AntonyCorbett** [comment]
@ilikelinux69 Sorry - I have no plans to port it, but the code is open and should be reasonably straightforward. I'd suggest starting with the console aopplication rather than the GUI app.

**Comment by SuperJC710e** [comment]
I recently discovered a way that seems to work using wine while looking for a way to run another dotnet based program. Here's the steps (mostly done from the command line, so get your terminal open!):

```
env WINEPREFIX=$HOME/winedotnet wineboot --init
env WINEPREFIX=$HOME/winedotnet winetricks dotnet40 corefonts
env WINEPREFIX=$HOME/winedotnet winetricks win7
env WINEPREFIX=$HOME/winedotnet winecfg
```
In the `winecfg` GUI, click on the "Drives" tab and click on "Autodetect". Check the list of drives, but most of what you want should be there. Then click "Okay"

Download the necessary version of dotnet and install it

```
wget -c 'https://download.microsoft.com/download/F/9/4/F942F07D-F26F-4F30-B4E3-EBD54FABA377/NDP462-KB3151800-x86-x64-AllOS-ENU.exe' -O ~/Downloads/NDP462-KB3151800-x86-x64-AllOS-ENU.exe
env WINEPREFIX=$HOME/winedotnet wine ~/Downloads/NDP462-KB3151800-x86-x64-AllOS-ENU.exe /q
```

Download the latest release of JWLMerge, either from the website or by modifying this command:

```
wget -c 'https://github.com/AntonyCorbett/JWLMerge/releases/download/1.0.0.33/' -O ~/Downloads/JWLMergeSetup.exe
```

Install JWLMerge. Most distros should just add a shortcut to the program to your menu.

```
env WINEPREFIX=$HOME/winedotnet wine ~/Downloads/JWLMergeSetup.exe
```
Hope this helps!

Jason

**Comment by abdon-copper** [comment]
Alternatively, you can run https://merge-jwl.netlify.app/ in a browser on Android (uses WebAssembly). The source code of this port can be found here https://github.com/abdon-gadgets/merge-jwl. It also has a simple CLI for Linux. Though it is still work in progress.
