### ISSUE TITLE
Problems with Creating Backup File

### ISSUE THREAD

**Issue by ctjones15** [AntonyCorbett/JWLMerge#16]
Hello, I'm having problems creating backup files using the application. When the program creates the file it no longer exists or is unreadable and shows up in my recent files as having no data. I don't understand why. 

I follow the main steps:
1. I open the application 
2. Drag the files I wish to merge
3. Click merge
4 Choose filename and also place to save file
5. When I go to find the file it's not there
6. When I find the name of the file in my recent files it's not openable or has 0 bytes.

Can you help me please? Thank you so much!

Windows 10 version 1809
Lenovo 720 Yoga

![Screenshot (228)](https://user-images.githubusercontent.com/50301388/57198217-b06f7880-6f46-11e9-9903-5f8cbc029178.png)
![Screenshot (229)](https://user-images.githubusercontent.com/50301388/57198219-b49b9600-6f46-11e9-8f3f-494d9ba6fd92.png)
![Screenshot (230)](https://user-images.githubusercontent.com/50301388/57198223-b8c7b380-6f46-11e9-9c35-f4f078e663dd.png)

**Comment by AntonyCorbett** [comment]
Perhaps you would send a copy of the log file for the day (Documents\JWLMerge\Logs\...). It may tell us why the merge failed.

**Comment by ctjones15** [comment]
Sure! I apologize for not doing so earlier. Please see below. I look forward to your reply:

[log-20190505.txt](https://github.com/AntonyCorbett/JWLMerge/files/3147219/log-20190505.txt)

Sincerely, 
Chris Jones

**Comment by AntonyCorbett** [comment]
@ctjones15 Thanks. Unfortunately, the log file doesn't provide sufficient information for me to diagnose the issue. Would it be possible to send both source files so I can reproduce the problem please? You can post privately to the SoundBox portal: https://soundbox.on.spiceworks.com/portal

**Comment by AntonyCorbett** [comment]
Issue resolved
