### ISSUE TITLE
Losing Highlights

### ISSUE THREAD

**Issue by jszalma** [AntonyCorbett/JWLMerge#17]
When highlighting my current study WT on my iPhone and then saving both it and my iPad data files, merging them and then restoring that new singular file, I'm keeping all my notes, and tabs but losing my highlights. Looking back, I see that I've lost a bit of my highlights in my Bible and study publications, but all the person study notes are there.  

I'm not using the JW Library Windows app, just between my two devices.

**Comment by benshemmeld** [comment]
I'm experiencing the same issue when merging data files from my iPad and Windows device.

**Comment by AntonyCorbett** [comment]
@jszalma @benshemmeld Thanks for your feedback. Is it possible to send me your 2 original backup files so that I can investigate the issue please? If so, you can send to this email address where I am the only recipient: help@soundbox.on.spiceworks.com

Also indicate the publication / article where highlights are missing once merged.

Thanks
Antony

**Comment by AntonyCorbett** [comment]
@jszalma Thanks for sending me sample backup files. I merged the two backup files and then imported the result and found no problem - both para 1 and para 2 highlights were present. However, the merged file that you supplied does _not_ contain the highlighting so I suspect you may be using an older version of JWLMerge, Please advise which version you are using and also try teh latest pre-release "1.0.0.24"

**Comment by benshemmeld** [comment]
@AntonyCorbett  thanks for looking into the issue.  I was about to send you my sample files when I saw your message above.  It looks like there may be an issue with the Installer for 1.0.0.24.  I built JWLMerge from the latest source code and it worked successfully (preserving the highlighting).  However, when using the installer the resulting merged file is missing the highlighting.

**Comment by AntonyCorbett** [comment]
@benshemmeld thanks - yes you're right. The source for the pre-releases was never pushed. Now fixed in 1.0.0.25. Thanks for your help!

**Comment by jszalma** [comment]
Thanks so much!
