### ISSUE TITLE
CLI documentation is needed

### ISSUE THREAD

**Issue by goodniceweb** [AntonyCorbett/JWLMerge#18]
Hi Antony!

I'm very happy with your project. Thank you for all the effort on this. It really helped me a lot.  That's why I want to create a web version of it (for linux/mac users for ex.) Could you please provide some documentation on CLI and how to use it?

I'm not really C# guy. I've tried to go through code but did not understand how should it work.  

I also saw you wanted to add a few new options to CLI. But for this issue I'd just document what you already have, without implementing new functionality.

If you need any help with that, please let me know. I can try to help on my own or find someone who knows C# better than me 🙂

**Comment by AntonyCorbett** [comment]
@goodniceweb You're right - theer's no documentation for the CLI. If you run the executable at the command prompt it does provide some simple help. Just specify the names of the backup files as parameters. the tool will then generate a merged file in the current folder with a name that begings "merged..." Hope that helps. Regards, Antony
