### ISSUE TITLE
How can I select where I would attach my note

### ISSUE THREAD

**Issue by SamaSer** [AntonyCorbett/JWLMerge#19]
Hi.

I have to take many notes in next 2 months because I attend a theocratic school and I think that I can't attach every note where exactly I desire, because I have not a lot of time between one answer and other.

I think that I will create many notes without attaching it to a specific text or paragraph. If I will do it maybe my notes will not be very useful.

My question is: 

It's possible to enter in the backup code and insert a part of code to declare the "place" (a Bible text or paragraph of some pubblication...) where I desire to visualize my note?

Thanks a lot

**Comment by AntonyCorbett** [comment]
@SamaSer You can take ad-hoc notes in JWL, but there is no way to attach these afterwards to a Bible verse or selected text in a publication - they will always remain stand-alone notes. So the only way I can see you doing this at the moment is to create notes electroncially in a text editor then at a later stage specify the appropriate Bible verses and use the function to import Bible notes as described in the wiki (https://github.com/AntonyCorbett/JWLMerge/wiki). 

Hope this helps.
Antony
