### ISSUE TITLE
Favoriten Anzeige fehlerhaft

### ISSUE THREAD

**Issue by Peter-66** [AntonyCorbett/JWLMerge#21]
Hallo,
leider ist mein Englisch sehr schlecht und ich hoffe dennoch euf eine kleine Hilfe von Euch.
Ich habe seit Monaten das Problem, dass in der Favoritenanzeige meiner JW Library die Bibel (Rbi8) angezeig wird und sich nicht löschen/ausblenden lässt. (Fragt mich bitte nicht, wie sie dahin gekommen ist. Ich weiß es nicht)

Auch wenn ich den Download der Bibel als ganzes gelöscht hatte, wurde sie nach dem erneuten Download wieder unter Favoriten angezeigt.

Das gleiche Problem tritt auf, wenn ich bei einem Neuen Gerät (Android oder Windows) die Library komplett neu installiere und danach meine Sicherung einspiele. Danach wird die Rbi8 wieder in meinen Favoriten angezeigt.

Gibt es eine Möglichkeit die Sicherungsdatei zu bearbeiten und die importierten Favoriten zu bearbeiten?

Kann mir jemand helfen diesen Bug zu lösen?
Aktuelle Ansicht meiner Favoriten
![grafik](https://user-images.githubusercontent.com/57788402/68923440-9ed11e00-077e-11ea-90ee-826b09582d13.png)

Vielen Dank vorab

**Comment by Peter-66** [comment]
Hallo Antony,
vielen Dank für die schnelle Antwort.
Ich kann mit dem Programm JWLMerge die Sicherung einsehen, aber nicht editieren oder die Zeile löschen.
EIne Funktion wäre hilfreich.
Aber mit welchem Tool kann man die Sicherungsdatei bearbeiten?

Vielen Dank und übrigends tolle Arbeit
Peter

**Comment by AntonyCorbett** [comment]
The backup file is actually a standard zip archive, so if you replace the ".jwlibrary" extnsion with ".zip" you can unzip its contents which should include a SQLite database file named "userData.db". You can then open this database using a SQLite client tool such as "SQLite Expert", open up the tables and make changes. When you have finsihed you'll need to put the modified userData.db file back into the archive and then rename the extension to ".jwlibrary". Of course, these steps require some skill and a bit of care!

**Comment by Peter-66** [comment]
Hello Antony,
I have the Tool SQLite Client.
I open the backupfile (it works good)
I extract the userDB.db
Start the Client and find the tables
Affter that I delete the first line with the value 2 in the column "TagId" 
After writing back and import... there was no result.
Sure, I misunderstood something
I send you a picture of the first line I deleted (that was still the original)
![grafik](https://user-images.githubusercontent.com/57788402/68964535-e46f0480-07d9-11ea-9c44-6b25e28cc8d0.png)

Wich line is the right one to delete?

**Comment by AntonyCorbett** [comment]
TagId = 1
Position = 2

**Comment by Peter-66** [comment]
Just wonderful. Thanks alot.
Finally, this lethal mistake is gone.
You are great.
I had overlooked that I have to sort the column first.
Simply great.
It works now

**Comment by AntonyCorbett** [comment]
Well done! 👍🏻
