### ISSUE TITLE
Run JWLMerge under Wine

### ISSUE THREAD

**Issue by SuperJC710e** [AntonyCorbett/JWLMerge#23]
I know this has been requested a couple of times, and closed, however, I've been able to get JWLMerge to run under wine. I created a wiki page with some brief instructions should you care to merge it into your wiki...

They are here: [https://github.com/SuperJC710e/JWLMerge/wiki/Running-Under-Wine](https://github.com/SuperJC710e/JWLMerge/wiki/Running-Under-Wine) (This is the URL to clone it: [https://github.com/SuperJC710e/JWLMerge.wiki.git](https://github.com/SuperJC710e/JWLMerge.wiki.git) ) 

The full forked repo is here: [https://github.com/SuperJC710e/JWLMerge](https://github.com/SuperJC710e/JWLMerge)

I think you could use the instructions provided here to pull the changes: [https://stackoverflow.com/a/56810747](https://stackoverflow.com/a/56810747)

**Comment by AntonyCorbett** [comment]
@SuperJC710e Sorry for the delay in responding. Thanks for your work on this. I have decided to post a link to your fork and to the instructions on the repo readme file. Hope that's ok.
