### ISSUE TITLE
Specify JWLMergeCLI output folder

### ISSUE THREAD

**Issue by erhardtv** [AntonyCorbett/JWLMerge#24]
Hi there

To automate the merger of files from various devices I'm writing a powershell script to run the merge but I can't specify the output folder as CLI only writes to the program folder and needs elevated rights.

I want to specify the output folder so that my devices can get the latest file from the merge output. The source and output files are all on OneDrive.

**Comment by marknpt** [comment]
I would second erhardtv request, perhaps an option to choose output location

**Comment by AntonyCorbett** [comment]
@erhardtv @marknpt The output file path can now be specified on the commandline using --output (or -o). For example:

JwlMergeCLI.exe backup1.jwlibrary backup2.jwlibrary -o result.jwlibrary
