### ISSUE TITLE
Can't Drag and Drop With version 1.1.0.2

### ISSUE THREAD

**Issue by alfredkusuma** [AntonyCorbett/JWLMerge#27]
Dear Brother Corbett,

I Have an issue with the JWLMerge, that i can't drag and drop any .jwlibrary files. old and new files (before and after jw library have 2 new color of highlighters)
please help me. 

I am using Win10 64
JW Library 11.5

Thank you in advance

Alfred

**Comment by AntonyCorbett** [comment]
@alfredkusuma Please see #25. The latest pre release should work. Regards, Antony

**Comment by alfredkusuma** [comment]
thanks for your reply.
yes. i already read it.
your latest pre release is the 11.0.2 right?
it still not work for me.

**Comment by AntonyCorbett** [comment]
1.1.0.2

If that's the version you are using, are you sure you are trying to drop a backup file created with the latest version of JWL? If so please would you send me the log file?

Thanks
Antony

**Comment by alfredkusuma** [comment]
[UserDataBackup_2020-04-12_Samsung_SM-T835.jwlibrary.zip](https://github.com/AntonyCorbett/JWLMerge/files/4465398/UserDataBackup_2020-04-12_Samsung_SM-T835.jwlibrary.zip)
[UserDataBackup_2020-04-11_OPPO_CPH1907.jwlibrary.zip](https://github.com/AntonyCorbett/JWLMerge/files/4465399/UserDataBackup_2020-04-11_OPPO_CPH1907.jwlibrary.zip)

**Comment by alfredkusuma** [comment]
my bad. it is only the extension problem.
.jwlibrary.zip
just delete the .zip.
now it is work.

thanks
Alfred
