### ISSUE TITLE
ausstehende Updates - Publikation aktualisiert nicht

### ISSUE THREAD

**Issue by Peter-66** [AntonyCorbett/JWLMerge#28]
Ein ausstehendes Update (eines älteren Arbeitsheftes-Dez 2019) will sich einfach nicht aktualisieren.
Immer und immer wieder lädt er es herunter. Am Ende steht es aber immer wieder als Update drinnen?

Hat jemand eine Lösung?

**Comment by Peter-66** [comment]
https://github.com/AntonyCorbett/JWLMerge/issues/28#issue-600511598

**Comment by AntonyCorbett** [comment]
@Peter-66 I'm sorry this Issues page is for the JWLMerge application, not JW Library.  Let me know if I misunderstood your question. Regards, Antony
