### ISSUE TITLE
Convert 11.5 backup file to a pre 11.5 file?

### ISSUE THREAD

**Issue by DarkLordGMS** [AntonyCorbett/JWLMerge#29]
Hello brother Colbett. 

I'm having an issue with two Android tablets from two brothers in my congregation. The tablets have been force closing since the new 11.5 version update. I've tried everything but this new version definitely doesn't work so I created a backup file of their notes and rolled back the app to version 11.4.2. However, because of the new v7 database, I can't restore it. I would need to "downgrade" the backup file. Do you have any ideas on how I can do this?

I'm an advanced user so feel free to guide me on how I could do this.

**Comment by AntonyCorbett** [comment]
@DarkLordGMS It would be a manual process involving the use of an Sqlite editor (to edit the databases). You would need an empty v5 backup. Load that along with the v7 backup into the Sqlite editor (e.g. SQLite Expert Personal) and copy data over from the v7 backup to the v5 one. The backup files are zip archives which need unzipping before you can gain access to the database files.
