### ISSUE TITLE
File not visible in ios

### ISSUE THREAD

**Issue by sdan000** [AntonyCorbett/JWLMerge#30]
**After updating program (April version) then merging my ios files in JWL on my desktop I uploaded it to icloud**
The file does not show up in JW library restore a backup list.

**To Reproduce**
After merging files in windows 10
1. Upload merged file to icloud
2. Click on restore a backup in JW library
3. List of all backup files including the one made for recent merge appears but not the uploaded file.
[log-20200615.txt](https://github.com/AntonyCorbett/JWLMerge/files/4780980/log-20200615.txt)

**Expected behavior**
Once uploaded to icloud, hit restore a backup in JW library and uploaded file should be present then click it to initiate backup.

**Screenshots**
Last Merged file named Merge#5 not on list in JW Library
![IMG_0901](https://user-images.githubusercontent.com/66959052/84673297-e5971a00-aeff-11ea-85f3-ed3cbbc5a892.PNG)

(bottom shows image of file in icloud drive)
**Desktop (Lenovo ideapad s145):**
 - Windows version 10
 - Icloud
- IOS Ipad/iphone
<img width="1112" alt="PNG image" src="https://user-images.githubusercontent.com/66959052/84672777-538f1180-aeff-11ea-8c4f-e1483ab7f19c.png">

**Comment by AntonyCorbett** [comment]
@sdan000 your final screenshot (restoring into JWL) shows that you are looking at "Recents" rather than a comprehensive list of files. Change to "Browse".

**Comment by sdan000** [comment]
Hmm..Never thought that could be the case but i guess thats why they included a seach feature. Thank you very much ansd thanks for the program. It puts me ahead of the curve. Hopefully the org will implement their own soon so those less tech than even me can take advantage. Thanks again!
