### ISSUE TITLE
Older Import Files

### ISSUE THREAD

**Issue by Algajo** [AntonyCorbett/JWLMerge#31]
I have a lot of files that I wanted to merge and it seems that files older than January 2020 don't merge.  Is it possible to add or enable capability for older files?

**Comment by AntonyCorbett** [comment]
@Algajo There was a change in the JWL backup file format (or at least the internal database schema). There is no real need to maintain backward compatibility because JWL itself provides the upgrade function - just restore your old backup to JWL and then create a new backup.
