### ISSUE TITLE
Drag and Drop not working

### ISSUE THREAD

**Issue by edaptive** [AntonyCorbett/JWLMerge#32]
I just installed JWLMerge, and the application opens fine. But every time I try to drag and drop the JWLibrary files nothing happens, it never copies over. Any ideas?

**Comment by AntonyCorbett** [comment]
JWL database schema has been updated in the latest version so I will need to do some work to bring JWL Merge up to date.

**Comment by AntonyCorbett** [comment]
@edaptive Fixed in latest release

**Comment by edaptive** [comment]
Thank you!
