### ISSUE TITLE
InputField is never instantiated

### ISSUE THREAD

**Issue by abdon-copper** [AntonyCorbett/JWLMerge#34]
The class `InputField` is never instantiated.

**To Reproduce**
1. In Visual Studio, search for references to `InputField`.
2. See that the no input fields are ever read from the database, the list will stay empty.

**Expected behavior**
I'm not sure what the meaning is of `InputField`, but it should not get lost during merging. Some code like this could be added:
```cs
result.InputFields.AddRange(ReadAllRows(connection, ReadInputField));
```

**Version**
Git ref 2644a343e2f1b0326616e683bdb64d0cd6e4c9a4

Thanks for this useful project!

**Comment by AntonyCorbett** [comment]
@abdon-copper Thanks. I did consider this when it was introduced in the most recent DB update (v8). However, AFAIK, it is unused in the current schema. Unless we can understand the semantics of the InputField table I can't see how to properly merge the data. Reading the data from the database as you describe would certainly be the first step when we know more about it.

**Comment by AntonyCorbett** [comment]
@abdon-copper Now supported. Thanks for your help
