### ISSUE TITLE
Backup File Format Error

### ISSUE THREAD

**Issue by GP90JW** [AntonyCorbett/JWLMerge#35]
**Describe the bug**
I have four different devices, three Win10 and one Android 9. All four have current versions of JW Library. The backup file for one of the Win10 devices, "Vision" is not being accepted by JWL. JWL was updated at the date of writing this report. Each Win10 device is up to date with Microsoft updates and have no issues.

**To Reproduce**
1. Drag all four JW Library backups into JWL
2. See error " Backup File Format Error" (See screenshot)
3. Drag individual "problem" backup into JWL
4. Same issue. (See screenshot)

**Expected behavior**
To see all four backups indicated in JWL ready to be merged.

**Screenshots**
Screenshot provided.

**Desktop (please complete the following information):**
 - "Vision" Windows 10 (ver 2004, OS build 19041.508)
 - JWL Merge 1.1.05
 - JW Library 1.1.6.1 (67449)

![Screenshot 2020-09-29 125703](https://user-images.githubusercontent.com/72078776/94555499-90cfa300-0253-11eb-8d5b-db2a8135d06d.jpg)

Thank you for considering my problem.

Graham.

**Comment by AntonyCorbett** [comment]
@GP90JW The error message indicates that the backup file is an older version. You can only use it in JWLMerge if it is updated to the latest. This is typically done by loading it into JWL and then creating a new backup.

**Comment by GP90JW** [comment]
@AntonyCorbett Thank you for your advice. I'm sure there is something I'm doing wrong here. I've followed the steps you have given. Prior to your advice I've confirmed the latest versions of JWLibrary and JWMerge. I then did the following:

Exported UserData from JWLibrary on the Win10 device I've named as "Vision". As part of the export I renamed the UserData by suffixing "fixed" to the filename to differentiate it. So this UserData now has the filename, "fixedUserDataBackup_2020-10-06_VISION.jwlibrary"

Imported that same UserData back into JWLibrary on "Vision"

Exported Userdata from JWLibrary on "Vision" again.

Attempted to transfer that exported UserData into JWMerge.

The same error was reported: [see attachment]

I'm experiencing this issue with the same UserData file no matter which Win10 device I attempt merging on with JWMerge.  The device I call "Vision" is one of my most often used devices, as I do a lot of studying and adding notes as I travel and as preparation for conducting Bible Studies. This is my ministry tablet.

![JML Issue 2020-10-06 192513](https://user-images.githubusercontent.com/72078776/95244433-d965fe00-0809-11eb-8ed9-bd57ead7e3eb.jpg)

**Comment by AntonyCorbett** [comment]
@GP90JW Hello Graham. Would you consider sending me a copy of your backup file please? I would treat it confidentially and delete it as soon as possible.

**Comment by GP90JW** [comment]
Do I send it by replying to this email, or through GitHub?

**Comment by AntonyCorbett** [comment]
@GP90JW by email please. This chat is public.

**Comment by AntonyCorbett** [comment]
@GP90JW my email address is above

**Comment by AntonyCorbett** [comment]
Closing now, but please re-open if needed.
