### ISSUE TITLE
JW Library Sign Language

### ISSUE THREAD

**Issue by aleraniere** [AntonyCorbett/JWLMerge#36]
Hi!

Thank you very much for your hard work in developing and maintaining this app so useful to us!

I would like to know if it would be possible to adapt or create an application that merges the backup files of the JW Library Sign Language. It would be very useful for us!

Thanks for listening!

**Comment by AntonyCorbett** [comment]
@aleraniere Thanks for your suggestion.

**Comment by kyudoc** [comment]
> @aleraniere Thanks for your suggestion.

I really need it.

Thanks!

**Comment by AntonyCorbett** [comment]
@aleraniere I've had a look at this, but there are too many differences to adapt the existing code to accommodate the Sign Language backup files. It would need someone else to pick this up, preferably someone familiar with the Sign Language app.

**Comment by pliniobrunelli** [comment]
I looked for some utility to merge JW Sign Language files and couldn't find any. So I decided to create my own utility. I published it today. There is still much room for improvement, but it's working.

https://github.com/pliniobrunelli/JWLSLMerge/releases/tag/1.0
