### ISSUE TITLE
Export to excel

### ISSUE THREAD

**Issue by Leroyjd123** [AntonyCorbett/JWLMerge#38]
Hi,

Thanks for creating this useful application.

Would it be possible to view the notes individually and be able to export them to excel, or also to have a feature wherein we can import specific notes/bookmarks?

For example, a table having the below columns can be designed:
Publication | Chapter | Verse/Para | Note | Tags

Thanks

**Comment by AntonyCorbett** [comment]
@Leroyjd123 Use the "Details" window to show Notes. You can select all and copy them to the clipboard for transfer to Excel. You can use the same Window to Import Bible notes. Does this cover your request?

**Comment by Leroyjd123** [comment]
@AntonyCorbett I have tried doing that, and it works fine, but certain details, such as which scripture was the note created or what tags a particular note has, is not available.
So what I meant was something wherein, I could see the note and the verse to which it was linked.

Thanks for responding so quickly!

**Comment by AntonyCorbett** [comment]
@Leroyjd123 The latest pre-release version (v1.2.0.1) contains a function to export Bible notes to Excel. Use the Ellipsis button next to the "DETAILS" button. Are you able to test and provide feedback please?

**Comment by Leroyjd123** [comment]
@AntonyCorbett 
I have just downloaded the prerelease and tried out the export feature, and it's working really well.
I will try using it more fully this week and will let you know if I get any issues.

Thanks again for this feature!!
