### ISSUE TITLE
Merge JW Sign Language playlists?

### ISSUE THREAD

**Issue by aslcouple** [AntonyCorbett/JWLMerge#40]
Hello my brother! Thank you so much for an amazing tool!

Would it be possible to do the same merge function for the playlists in the JW Sign Language app (JWSL)?

They are still .jwlibrary files but instead of Notes, Bookmarks, Underlining, and Tags the JWSL app only has playlists containing media entries with start/stop times and a end of file functionality (continue, stop, freeze, repeat). I've attached an example of an exported file containing 2 such playlists.

![screenshot](https://user-images.githubusercontent.com/18621101/112568298-9a783480-8db8-11eb-89ee-9fd4547ee75e.png)

[JWSL_UserdataBackup_2021-03-25.jwlibrary.txt](https://github.com/AntonyCorbett/JWLMerge/files/6208930/JWSL_UserdataBackup_2021-03-25.jwlibrary.txt)

I tried importing JWSL into JWLmerge but it threw an error as I'm sure there are some significant differences in the content of the exported files. Just an idea that would probably benefit plenty of those involved in sign language groups and congregations.

Thank you!

**Comment by AntonyCorbett** [comment]
@aslcouple Thanks for your suggestion. See also #36

**Comment by pliniobrunelli** [comment]
I looked for some utility to merge JW Sign Language files and couldn't find any. So I decided to create my own utility. I published it today. There is still much room for improvement, but it's working.

https://github.com/pliniobrunelli/JWLSLMerge/releases/tag/1.0
