### ISSUE TITLE
Backup File Format Error

### ISSUE THREAD

**Issue by Gary-eng** [AntonyCorbett/JWLMerge#41]
In the past, dragging and dropping the JW Library backup files onto the JWLMerge window has always worked as expected.
Each one appears as a box within the program window, and I could merge them successfully.

However, this latest version appears to be broken on my system.

I cannot drag and drop the JW Library backup files from either my Android phone or my iPad.
Both, the Android and the iPad files consistently cause an error as shown in the attached screenshot.
![25-03-2021 9-53-14 PM](https://user-images.githubusercontent.com/81401538/112576115-4751b200-8db7-11eb-9314-6f1f13b4d0f5.png)

I can only drag and drop the backup made from the Windows version of JW Library.
![25-03-2021 10-15-37 PM](https://user-images.githubusercontent.com/81401538/112576398-d19a1600-8db7-11eb-9cc2-83c2b0ffdeb1.png)

Android and iPad JW Library versions are both latest updates, version 12.3.4 (98062)
The Windows JW Library is 12.3.118 (96175)

I've tried dragging the backups onto the JWLMerge window in various orders, (iPad first, phone first, Windows first...), and it makes no difference to the outcome.
I've also tried creating brand new backups in the iPad and the Android devices, just in case they might have been corrupted in some way.
The error message persists.
The error popup claims that details follow, but there's nothing. 

I've tried completely uninstalling JWLMerge, including registry entries, and reinstalling. The same issue persists.

Windows10 Home 1909
OS Build 18363.1441

**Comment by AntonyCorbett** [comment]
@Gary-eng please would you send me a copy of one of the failing backup files? jwmege@corbetts.org.uk

**Comment by AntonyCorbett** [comment]
@Gary-eng The log file may also reveal the nature of the problem. (Documents\JWLMerge\Logs)

**Comment by Gary-eng** [comment]
Thanks for the help Antony.
Looking more closely, it appears OneDrive has made only the Windows backup available on my device; the others are only available "when online". I've always created and restored the backups to and from my OneDrive account, but this is some kind of new behaviour with OneDrive. It's never before locked some files to only being available to me in the cloud, while others are available on my laptop.

But once I manually made them all available offline, then JWLMerge can access them.
