### ISSUE TITLE
With Tags ticked file merge files fails to create

### ISSUE THREAD

**Issue by IDSAU** [AntonyCorbett/JWLMerge#43]
1. Exported from each device .jwlibrary backup 
2. Load JW Merge (great tool thanks)
3. Drop in 3 files to merge
![2021-04-14 (1)](https://user-images.githubusercontent.com/82516416/114710983-fe12d380-9d60-11eb-8ebd-76b5c89d356c.png)
As shown in image when Tags is ticked, but no merge files is created.

![2021-04-14 (2)](https://user-images.githubusercontent.com/82516416/114712002-2f3fd380-9d62-11eb-9872-111eeee5bd1a.png)
As shown in image when Tags is not ticked, the merge files is created.

It seems to be an issue with my Tags, but unsure how I can fix this.

**Comment by AntonyCorbett** [comment]
@IDSAU First check that you are using the latest version of JwlMerge. If you are, please post the log file which is in Documents\JWLMerge\Logs

**Comment by IDSAU** [comment]
Thanks for reply
[log-20210414.txt](https://github.com/AntonyCorbett/JWLMerge/files/6311262/log-20210414.txt)

Latest Version  JWLMerge 1.1.0.7

**Comment by AntonyCorbett** [comment]
I can see that there was an error merging the location data. Would it be possible to send me the backup files please? It would only be me who looks at them and I would delete them asap. If so, please email jwlmerge@corbetts.org.uk

**Comment by AntonyCorbett** [comment]
@IDSAU Thanks for the files. Identified as a corruption in one of the source databases. The Location table contains 2 rows that violate one of the databases unique constraints. These must have been inserted before the constraint was added to the database in a JW Library upgrade.

**Comment by AntonyCorbett** [comment]
Fix is to perform a source validation check, stripping out "duplicate" Locations rows if needed.
