### ISSUE TITLE
Backup Full JW Library

### ISSUE THREAD

**Issue by verdura** [AntonyCorbett/JWLMerge#44]
Hi,

Thanks a lot for your work!
Would you consider making a full backup of JW Library to transfer for another PC? Let's say I want to get all the publications on the new pc (some of the publications are not public and are time consuming to get. Talks for example are 180 plus...)
It would be nice to get all the publications transferable to a new pc (or a way to backup!)

Thanks

**Comment by AntonyCorbett** [comment]
@verdura This is beyond the scope of the JWL Merge project but I believe it is possible to accomplish the transfer yourself if you are reasonably familiar with the Windows file system. The process is as follows:

1. Set up JWL on your new "source" PC
2. Launch JWL and allow it to initialise (few minutes)
3. Close JWL on source and destination PCs
3. Copy all files and sub-folders from some of your source PC's LocalData folders (see below) to the corresponding folders on your destination PC

The folders to copy are as follows:

- %LocalAppData%\Packages\WatchtowerBibleandTractSo.45909CDBADF3C_5rz59y55nfz3e\LocalState\Data
- %LocalAppData%\Packages\WatchtowerBibleandTractSo.45909CDBADF3C_5rz59y55nfz3e\LocalState\Publications
- %LocalAppData%\Packages\WatchtowerBibleandTractSo.45909CDBADF3C_5rz59y55nfz3e\LocalState\Tiles
- Contents of the Video and Audio folders specified in JWL Settings

I haven't tested the above recently, but it worked when I last did this a couple of years ago. Please report back if you try it.

**Comment by skneife** [comment]
Thank you Antony for the details of the recovery process of JW Library after reinstallation.

With JW Library version 13.4.59 (248747) I had to copy the entire contents of the LocaState folder to make it work.

Sam
