### ISSUE TITLE
Import Bible Notes Exported from JWLMerge

### ISSUE THREAD

**Issue by lukefarr** [AntonyCorbett/JWLMerge#45]
**Is your feature request related to a problem? Please describe.**
If you add a note on a confidential publication, text from the confidential document will be included in the note. If this note is merged although the confidential publication may not be accessed, text can still be read. Selective tags to merge would filter out any notes that have been tagged but this is unlikely to catch everything.

**Describe the solution you'd like**
Exporting Bible Notes is fantastic. The only notes exported in the Bible itself. If the excel exported could be imported this would enable me to have a backup that only contains notes in my Bible.

**Describe alternatives you've considered**
Selective tags to merge would work to a certain extent but you would need to have a tag that you would remember to add everytime you make a note in a confidential publication. 
Selective publication merges is another possiblilty but I would imagine this far more complex (similar to the other current enhancement request.

**Additional context**

**Comment by AntonyCorbett** [comment]
@lukefarr Thanks for your suggestion. I am already looking at a solution and should have something shortly.

**Comment by AntonyCorbett** [comment]
@lukefarr please see the latest pre-release. Marking as closed, but please reopen if needed
