### ISSUE TITLE
Tags not associated

### ISSUE THREAD

**Issue by Chiriat** [AntonyCorbett/JWLMerge#46]
**Describe the bug**
Thanks for this nice software. 
when I import a .txt file with Bible notes and choose a tag, this tag is then not associated with any notes in JWL.

**To Reproduce**

**Expected behavior**

each note should have the tag chosen when importing

**Screenshots**

**Desktop (please complete the following information):**
 - Windows10

thank you

**Comment by AntonyCorbett** [comment]
Are the notes imported without a tag, or is the import operation aborted?

**Comment by Chiriat** [comment]
the import works great with both the JFB commentary file and with another file I created with my notes. Any tags I choose from the list are not associated with the new imported notes

**Comment by AntonyCorbett** [comment]
@Chiriat Fixed in latest pre-release (1.2.0.5)
