### ISSUE TITLE
.jwlibrary file 

### ISSUE THREAD

**Issue by Jordan-Volcano** [AntonyCorbett/JWLMerge#5]
Hello,

Sorry for posting here, but i didn't see where i can pm you personnlay.

I'm wondering what structure are the .jwlibrary files
Maybe you can tell me ? how can i open it, and read it ?

I test your program, it's amazing !
Thanks a lot,
And sorry if it is not the place....

Jordan

**Comment by AntonyCorbett** [comment]
@Jordan-Volcano Hi. Sorry for the delay in responding. The files are simple zip archives. If you rename them to have a .zip extension you should then be able to open them to examine contents. The db file is in SqlLite format.

Kind regards
Antony
