### ISSUE TITLE
New Pre-Release

### ISSUE THREAD

**Issue by Chiriat** [AntonyCorbett/JWLMerge#50]
Hi Antony,

after installing .NET I keep getting the message that I need to install it and JWLMerge doesn’t start.

Tested on 2 machines with window 10
Thanks.

**Comment by AntonyCorbett** [comment]
@Chiriat - thanks for reporting, I can see the problem and will fix shortly.

**Comment by AntonyCorbett** [comment]
Now fixed. Thanks for testing. Please let me know if you have further problems / feedback.

**Comment by glenmwright** [comment]
I am still having this issue with version 1.3.0.2. After install, it prompts to install .Net 5.0, even though I have installed it.

**Comment by AntonyCorbett** [comment]
@glenmwright Thanks for your feedback. I'm struggling with packaging the app under .NET 5. Would you please uninstall JWLMerge, delete any remaining files in the installation folder, and finally reinstall? I have updated the installer to 1.3.0.3

**Comment by glenmwright** [comment]
Thank you Antony. I uninstalled, made sure the install directory was empty and installed 1.3.0.3. It still prompts to download .NET 5. I am running Windows 10 21H! 64-bit. I have .NET 5 64-bit uninstalled. I am happy continue to help in testing while you track it down.

**Comment by AntonyCorbett** [comment]
@glenmwright What is the exact text of the error message please?

**Comment by mur-dock** [comment]
I had the same issue. So I just installed .NET 5 Runtime 32-Bit (x86) and it works well. ;-)

**Comment by AntonyCorbett** [comment]
@mur-dock I understood that the runtime contained both 32 and 64 bit

**Comment by mur-dock** [comment]
> @mur-dock I understood that the runtime contained both 32 and 64 bit

So I did, but there are separate versions.

The recommended link after the prompt lead me to a choice between of two kind of runtimes (x64 + x86).
After I installed both of them it works (first 64-bit; after installed 32-bit everything is fine).

**Comment by glenmwright** [comment]
I hadn't thought of that. After installing the 32-bit (x86) version. It works fine.

**Comment by AntonyCorbett** [comment]
With .NET 5 it is possible to distribute the runtime with the app, but that would make the deliverable quite large!
