### ISSUE TITLE
CLI so I can automate the process?

### ISSUE THREAD

**Issue by webnoob** [AntonyCorbett/JWLMerge#54]
Thanks for the tool :)

I would like to set something up so my dropbox / onedrive folder account can be monitored and "wait" for new files, it will then process those files into a specified output.

Something like this would be good: 
```bash
jwlmerge.exe --files="pcFile.jwlibrary,ipadfile.jwlibrary" --output="mergedFile.jwlibrary"
```

I know this would lack the choosing of options but that could be factored in or just use this when you want a complete merge.

I could then write something to monitor my folder and run the merge automatically.

**Comment by AntonyCorbett** [comment]
@webnoob JWLMergeCLI.exe provides a command-line interface but I've just noticed that it's not available in the "portable" release; only if you use the installer.

**Comment by webnoob** [comment]
My apologies, I didn't even see that in the source 🙄 
I'll take a look - thanks.
