### ISSUE TITLE
BUG JWL merge is no more starting since update to newest version

### ISSUE THREAD

**Issue by ngsoftDE** [AntonyCorbett/JWLMerge#57]
**Describe the bug**
On start it only shows that i have to install .Net with an option to download from Microsoft.
But i ALREADY installed it!

**To Reproduce**
1. Just start 'JWL Merge' after installation
2. See error
3. Press Yes
4. Download .NET from Microsoft and install
5. start 'JWL Merge'  again
6. same error

**Expected behavior**
JWL Screen has to be shown.

**Screenshots**
[Image of Error.](http://2.ngsoft.de/p2RktYE)

**Desktop (please complete the following information):**
 - Windows 10  version 21H2
 - Other important information about your environment 64-Bit System

**Comment by AntonyCorbett** [comment]
@ngsoftDE I'm sorry, but it's another version that's needed (.NET 6 Desktop x86)

**Comment by AntonyCorbett** [comment]
@ngsoftDE ATM, I am keeping up with the rapid releases of .NET mainly because of the performance improvements to be gained during each revision. But it is a pain for the user! I may decide to bundle the runtime!

**Comment by ngsoftDE** [comment]
@AntonyCorbett Thanks for reply!

The Error window takes me to the .Net 5 Runtime Download page. Thanks for giving solution. I Downloaded .Net version 6 but it does not work. (even with x32-bit)

**Comment by AntonyCorbett** [comment]
Did you run the installer or use the zip file? The installer should have automatically installed the runtime.

**Comment by AntonyCorbett** [comment]
The required runtime is x86 Desktop .NET 6. Make sure you pick "Desktop"

**Comment by AntonyCorbett** [comment]
@ngsoftDE Have you been able to install yet?

**Comment by littlebull** [comment]
Hi,

I have the same problem. Installing .NET Desktop 6 x86 did not solve the problem.

Thanks for the gread tool BTW.

Regards
Julian

**Comment by AntonyCorbett** [comment]
@littlebull thanks for your report. Please would you check at the command prompt? type the following:

dotnet --info

This should list the various .net sdks and runtimes that are installed. If all is well, you should see a reference to **Microsoft.WindowsDesktop.App 6.0.1** under the list of **.NET runtimes installed**.

**Comment by littlebull** [comment]
Hi Antony,

this is the output:

```
.NET SDK (gemäß "global.json"):
 Version:   6.0.101
 Commit:    ef49f6213a

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by AntonyCorbett** [comment]
@littlebull Thanks. That looks fine. Would you mind downloading the zip file, unzipping it into a new folder anywhere on your drive, and then trying to launch the JWLMerge.exe file, please?

**Comment by littlebull** [comment]
@AntonyCorbett Same error message with the portable ZIP and JWLMerge.exe

**Comment by AntonyCorbett** [comment]
@littlebull Thanks for your patience. Please would you just check that the x86 desktop runtime is on your HD? It should be in the following folder (about 80MB):

\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.1

**Comment by littlebull** [comment]
@AntonyCorbett I can confirm, this directory is existent: 

`C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.1`

**Comment by ngsoftDE** [comment]
> Did you run the installer or use the zip file? The installer should have automatically installed the runtime.

I used the installer. But it does not work...

**Comment by AntonyCorbett** [comment]
@littlebull Please would you reinstall the runtime (.NET 6 x86 Desktop) and try again? The only thing I can think of at the moment is a corrupted installation.

**Comment by littlebull** [comment]
@AntonyCorbett I downloaded from here https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.1-windows-x86-installer and made a repair install. Did not change anything... Then tried to uninstall and reinstall. The same...

I am not sure, but the .NET installer look strange here:

![image](https://user-images.githubusercontent.com/16230940/147106913-134506f5-6d91-4888-a94c-2b7f23636144.png)

Looks like the installer does not know the installation path...

**Comment by AntonyCorbett** [comment]
@littlebull @ngsoftDE I've not been able to find any additional information on this issue. There are about 300 users currently using the latest version so I expect the problems you are facing with NET 6 compatibility may be isolated.

**Comment by DryBSMT** [comment]
Hello, I have a new installation of Windows 11 and have installed JWLMerge and I am having the same issue as @littlebull.  I have gone through and checked everything you have listed above.

You also asked him: 

> Please would you just check that the x86 desktop runtime is on your HD? It should be in the following folder (about 80MB):
> 
> \Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.1

There is no 80MB file in the folder but the entire folder is 79.7MB.

I will try and install on my Win10 computer at home and see if it works there.  I was excited to find this App and although I have not used it yet, I appreciate all the effort you must have put into it and all the time you must spend troubleshooting.

**Comment by AntonyCorbett** [comment]
@DryBSMT Thanks for your report. Please would you try today's build and let me know if it makes any difference?

**Comment by DryBSMT** [comment]
@AntonyCorbett I tried to install the latest build and the installer shows on my taskbar but there is no window,  Task manager shows it using the CPU and Memory but says 'Not Responding', although the CPU and Memory keep changing. 

![image](https://user-images.githubusercontent.com/97263599/148556349-3954142d-33b6-47b0-8f93-2a619b5d30c9.png)

I checked Add/Remove and the last version had installed apparently although I did not know it because nothing seemed to happen after the .net installation.  I should have tried to run it and see what happens but I just uninstalled it in case that was the issue with the latest builds installer.  I then rebooted to make sure the OS was fresh and tried the installer again.  Same issue.

I did not get a chance to try it at home on my win10.

**Comment by DryBSMT** [comment]
@AntonyCorbett I just downloaded the previous build again and strangely, the install went smoothly. I can't explain it.  I then tried to update thinking that perhaps it may work, but alas, same issue with installer not responding. 
The only thing I can think of is that rebooting after the install of .net 6.0.1 may have corrected something because I can't recall if I did it after the install yesterday.  I think I would have, just to check, but I just don't know.  I know I rebooted today before trying the previous build again.  I hope this is helpful information and if there is anything else I can do to help, let me know.

**Comment by AntonyCorbett** [comment]
@DryBSMT Yes - it looks like there is an issue with the installer. I've removed 2.0.0.8

**Comment by DryBSMT** [comment]
@AntonyCorbett I just tried my first merge and it went slick as a whistle!  So Awesome! Thank you Brother!

**Comment by AntonyCorbett** [comment]
@littlebull @ngsoftDE @DryBSMT Please would you try the latest pre-release build (2.0.0.9). This release includes the runtime embedded in it (which explains why the download is somewhat larger).

**Comment by littlebull** [comment]
@AntonyCorbett 2.0.0.9 works. Great, thank you very much for your support!!

**Comment by publisher76** [comment]
I was having an issue with the .NET error on Win 11. The 2.0.0.9 version fixed the issue, and all is good. Thank you very much!
