### ISSUE TITLE
Selective Tags to Merge

### ISSUE THREAD

**Issue by lukefarr** [AntonyCorbett/JWLMerge#7]
Dear Anthony. Fantastic work as always. 
This is not an issue at all but just an idea that others may find useful. If we could selectively merge notes with only certain tags that would be fantastic.
Feel free to delete as I mentioned this is not a "bug"
Many thanks,
Your brother,
Luke

**Comment by ShaunKrane** [comment]
Greetings Antony,

You are a true blessing brother!!! I have been puzzled on how to merge 4 different devices that have different notes. I agree with Luke that its not a bug but would be a great option to selectively merge notes with only certain tags. This would correct any issues where if there are 2 notes on the same item, scripture we could select which note to keep, would be a great feature that you need to share with the organization.

Keep on doing great things brother. Truly grateful for your expertise in this area.

Your spiritual brother,
Shaun Garza

**Comment by pkley** [comment]
Being able to select tags or alternatively select tags to NOT import would be fantastic. I'd like to have most everything on my work laptop but not confidential things...

**Comment by pkley** [comment]
Shaun, can you confirm that JWMerge will only keep one note per verse if there's a conflict, as in you've seen them disappear? I don't believe that's the case, but haven't tested.

Peter Kley

**Comment by AntonyCorbett** [comment]
@pkley Each note in the JWL "Notes" database table has a "Guid" value - a globally unique identifier. This is useful because we can retain the identifier during merge operations. Each note also has a "LastModfied" date/time stamp which helps in the situation where the same note exists on two devices and is updated on one or both - the merge operation will always use the most recent modification of the note. AFAIK, we support multiple notes per verse, but let me know if you have any difficulties.

**Comment by AntonyCorbett** [comment]
@lukefarr @pkley The latest pre-release includes a command to remove notes by Tag (use ellipsis on the backup file card). This command removes the relevant notes from the original backup file (i.e. it does not depend on a merge operation).

**Comment by lukefarr** [comment]
Dear Anthony. This is great news. Just trying to see how I download the prereleases for windows to give it a whirl

**Comment by lukefarr** [comment]
Really good! Found the prerelease and have started to play about. Really love the bible export too! Do you have plans to enable an import of that format rather than the txt file?
Thank you so so much.

**Comment by pkley** [comment]
I tried redacting but perhaps I misunderstood what it does. I was expecting
based on the description that you could overwrite a single tag, but it
overwrote ALL notes. Was that expected?

I was also personally hoping to be able to delete all notes associated with
a tag, as I have a tag called "Delete" which I use for temporary notes,
typically on timing for conducting the WT or bible study. This would help
me also remove certain notes by tag so no sensitive info is on my work
laptop but all the rest of my notes are.

**Comment by pkley** [comment]
Sorry, I missed the 1.2 release part...trying that!

Peter

**Comment by pkley** [comment]
Woohoo! 256 notes tagged Delete are now gone! Exactly what I was looking
for and everything else seems to be intact.

Thank you!!!!

Peter
