### ISSUE TITLE
plantage jw library

### ISSUE THREAD

**Issue by Riroux13** [AntonyCorbett/JWLMerge#71]
bonjour apres avoir combiné les sauvegardes avec jwl merge, je fait la sauvegarde sur ma tablette huawei lorsque je clique sur la sauvegarde jw library se ferme alors que je n'ai pas se problème sur pc ou mon xiaomi. Merci pour votre aide

**Comment by Riroux13** [comment]
bonjour apres avoir combiné les sauvegardes avec jwl merge, je fait la sauvegarde sur ma tablette huawei lorsque je clique sur la sauvegarde jw library se ferme alors que je n’ai pas se problème sur pc ou mon xiaomi. Merci pour votre aide

**Comment by AntonyCorbett** [comment]
@Riroux13 Thanks for the report. Sorry, I don't really have enough information to go on here.  I suspect that one of the source backups may be corrupt, so perhaps you could try importing them individually to the Huawei tablet to see if one or more of them causes the same issue.

**Comment by AntonyCorbett** [comment]
Closing as no response
