### ISSUE TITLE
JWL merge AUTO-SYNC

### ISSUE THREAD

**Issue by ngsoftDE** [AntonyCorbett/JWLMerge#73]
**Is your feature request related to a problem? Please describe.**
The problem is, that there is still NO AUTO-SYNC between all the android and windows devices

**Describe the solution you'd like**
php server script and maybe client app apk to auto-sync between all devices every 30 mins (or maybe fewer)

**Describe alternatives you've considered**
Theres no alternative at the web found by me

**Comment by AntonyCorbett** [comment]
Thanks for the suggestion, but this will never be a feature of JwlMerge.
