### ISSUE TITLE
Personal request: could  you share/add to wiki, the file/db formats of jw library?

### ISSUE THREAD

**Issue by realtebo** [AntonyCorbett/JWLMerge#78]
**Is your feature request related to a problem? Please describe.**
No, I simply would like to have documentation from someone already reverse-engeenered Jwlibrary

**Describe the solution you'd like**
Point me to documentation online fo jwlibrary file formats or add to wiki here

**Describe alternatives you've considered**
I'm trying since some months to understand sqlite db internal links beetweens tables and 'real objects' on screen

**Additional context**
I can add my email temporary here if you can/want.

**Comment by AntonyCorbett** [comment]
@realtebo - The schema files are available in this repo. The latest is Version008.txt

**Comment by realtebo** [comment]
I saw the schema, thanks... but I was looking for some 'description' of relations from what I see on the screen and what I can find on the db.

Anyway, even if it's a schema dump only of few file, it's usefull. Thanks again

**Comment by AntonyCorbett** [comment]
@realtebo JWLMerge.BackupFileServices/Models/DatabaseModels/

Comments in the above files may be of use
