### ISSUE TITLE
Missing signing certificate

### ISSUE THREAD

**Issue by DavidIQ** [AntonyCorbett/JWLMerge#8]
When attempting to build this project the following output is produced:
```
Error		Unable to find manifest signing certificate in the certificate store.	JWLMergeCLI
Warning		Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.	JWLMergeCLI
```
To get around this I'm having to go into the JWLMergeCLI project properties and uncheck the _Sign the ClickOnce manifests_ option under the _Signing_ tab. So either the certificate needs to be added to the repo or this option needs to be disabled, not sure which route you want to go.

**Comment by AntonyCorbett** [comment]
@DavidIQ Thanks for spotting this. Now fixed.
