### ISSUE TITLE
unconfirmed 448907 .crdownload

### ISSUE THREAD

**Issue by Savemynotes** [AntonyCorbett/JWLMerge#85]
**Describe the bug**
i download and the DL tag seize unconfirm 448907 .crdownload

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@Savemynotes - you are seeing the temporary download file. You need to click on the ellipsis in the browser's downloads area and "Keep" the downloaded file. This is part of Windows' attempts to avoid malware infection.
