### ISSUE TITLE
Please Update the Running Under Wine Reference

### ISSUE THREAD

**Issue by SuperJC710e** [AntonyCorbett/JWLMerge#90]
Hi Antony,

Thanks again for the program!

A note and request. My repo was never intended as a fork, but for the wiki notes on the subject of running your fine program under wine. The instruction I posted before on the Issue would have just brought the notes "in house". That said, could you instead just link to the Wiki page please?

[https://github.com/SuperJC710e/JWLMerge/wiki/Running-Under-Wine](https://github.com/SuperJC710e/JWLMerge/wiki/Running-Under-Wine)

Or if you want, you could incorporate those notes into your wiki.

Also, I just updated the notes, however, I only use the program occasionally (as I had, until recently reduced to using 1 device), so don't keep up-to-date on the most recent changes.

Side note: Any thoughts on writing the program with dotnet core so it could be cross platform? Just a question, I have no idea how difficult that might be...

**Comment by SuperJC710e** [comment]
Thanks @AntonyCorbett that looks great! I didn't want to give the impression that I was maintaining a fork of the code. I defiinitely do not have the C#/dotnet skills required. 

On your additional reply, that's great to know. I did see in the `csproj` files that it was using `net6.0` now, which is why I had to update my wine setup. Although I do not really know how to code in these languages, in my day job I am a DevOps Engineer, and the company I work at uses dotnet framework and now core quite extensively so I have become familiar with building the code in CI/CD pipelines at least. So I gave it a try, and you are correct, it does build nicely on Linux. I find I need to explicitly define the output, or else the program complains that it cannot access the path. This might have something to do with SELinux that Fedora uses, but I'm not sure. (I actually noticed a similar issue when running the CLI from wine. So just now I tried defining the output directory and file explicitly, and it also works.) Are there any "hidden" CLI switches available to select items like in the GUI? Also, can it merge more that 2 files on the CLI?

Anyway, thanks for the prompt update and the great programs! :)

**Comment by AntonyCorbett** [comment]
> I find I need to explicitly define the output, or else the program complains that it cannot access the path. 

you could raise a bug report on this.

> Are there any "hidden" CLI switches available to select items like in the GUI? Also, can it merge more that 2 files on the CLI?

no hidden switches. But you can specify any number of input files.
