### ISSUE TITLE
JWLMerge for JW Library Sing Language

### ISSUE THREAD

**Issue by CharllysFernandes** [AntonyCorbett/JWLMerge#91]
Would it be possible to have a version for the JW Library Sign Language? Creating a single file with all the playlist or merging backups as is currently done by JWMerge.

During a meeting we have many participants who add their backups. Which is always replaced by the current backup. Merging the data would allow you to have more control over the data that will be used in the meeting by seeing all the media that will be used.

**Comment by AntonyCorbett** [comment]
@CharllysFernandes Please see #40 and #36

**Comment by pliniobrunelli** [comment]
I looked for some utility to merge JW Sign Language files and couldn't find any. So I decided to create my own utility. I published it today. There is still much room for improvement, but it's working.

https://github.com/pliniobrunelli/JWLSLMerge/releases/tag/1.0

**Comment by CharllysFernandes** [comment]
Obrigado. Vou testar e implementar nas nossas reuniões.
