### ISSUE TITLE
Unable to manage JWL V14.x backup files

### ISSUE THREAD

**Issue by ColinWillies** [AntonyCorbett/JWLMerge#93]
**Describe the bug**
JWL Merge 2.1.0.4 appears to be unable to manage V14.x backup files

**To Reproduce**
1. Make a backup with JWL 14.x 
2. Attempt to side into JWL Merge
3. Nothing happens.

**Expected behavior**
1. Make a backup with JWL 14.x 
2. Slide it into JWL Merge.
3. Slide other files into JWL Merge.
4. Merge and save the merged backup file.
5. Import the merged backup file to target devices.

**Screenshots**

**Desktop (please complete the following information):**
Same behaviour with Backup files generated in Android 13 and Windows 11. 
Files created in Windows 10 and 11 and Android 13 created before JWL Upgrade to 14.x are still working.

**Comment by AntonyCorbett** [comment]
@ColinWillies Note that this project is no longer compatible with the latest version of the JW Library. In July 2023 the database schema was changed from v8 to v13 and I will not be updating JWLMerge to support the new version. In Jan 2023, the JW Library licence agreement was strengthened, but it also gave opportunity for 3rd party developers to apply for official permission to do the sort of work that is present in JWLMerge. I made an application in January but have not received permission, and in these circumstances feel it best to archive the project at this juncture. Thank you for your understanding, and for your valuable input and feedback on the project over the last 6 years.

**Comment by ColinWillies** [comment]
Thanks Anthony, this is disappointing but I understand. I rely heavily on being able to make changes on any device I have at my disposal and the I do a merge at least once a week to make sure I lose nothing when I restore on all of them... I will dig around a bit to see if I can source equivalent functionality - if not I guess I'll be doing a backup every time I us JWL and restoring the latest backup I have before I start an each device I use... Much more effort and much more risk but so be it... Thank you for your efforts over the years to support us :-)

**Comment by AntonyCorbett** [comment]
@ColinWillies Sorry to disappoint. I am clinging to the hope that I may get the necessary permission, but after 6 months I doubt it's forthcoming. There are some other projects and they may take a different view or have perhaps received permission. Best wishes, Antony
