### ISSUE TITLE
New Backup files to JWLibrary doesn't load - even with last update of JWLMerge 2.1.0.5

### ISSUE THREAD

**Issue by Maitre2Citrouille** [AntonyCorbett/JWLMerge#97]
**Describe the bug**
Could not load the new backup files from last version of JWLibrary

**To Reproduce**
1. Open JWLMerge (2.1.0.5)
2. Drag and drop JWLibrary backup files (last version)
3. See error the screenshot

**Expected behavior**
I expected that the files are fully loaded to merge them.

**Screenshots**
![image](https://github.com/AntonyCorbett/JWLMerge/assets/72652047/c1186e69-d42b-4046-98c6-224f56aad47e)

**Desktop (please complete the following information):**
 - Windows 11, 22H2, build 22621.1992

**Comment by AntonyCorbett** [comment]
@Maitre2Citrouille Note that this project is no longer compatible with the latest version of the JW Library. In July 2023 the database schema was changed from v8 to v13 and I will not be updating JWLMerge to support the new version. In Jan 2023, the JW Library licence agreement was strengthened, but it also gave opportunity for 3rd party developers to apply for official permission to do the sort of work that is present in JWLMerge. I made an application in January but have not received permission, and in these circumstances feel it best to archive the project at this juncture. Thank you for your understanding, and for your valuable input and feedback on the project over the last 6 years.

**Comment by lexiconwriter** [comment]
Really bad news. How to study at different place with different devices in the future? 😧

**Comment by Maitre2Citrouille** [comment]
Hello,

Thank you for feedback.

I understand perfectly your choice: if there is no permission, we respect
it.

Perhaps these very usefull option will be added in the future of JW Library.

I think the problem for the organization is to enable this feature without
risk that user use cloud drive to do it and to make this feature simple to
use and cross-platform without third party app.

Thank you that you answered me.

Le sam. 15 juil. 2023, 17:38, Antony Corbett ***@***.***> a
écrit :
